package com.log515.lambda.wherework.soap;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 06/09/2016
//
//---------------------------------------------------


public interface IServiceEvents
{
    public void Starting();
    public void Completed(OperationResult result);
}
